### ISSUE TITLE
크롤링 데이터 수집 문제

### ISSUE THREAD

**Issue by yungwangoh** [SEJONG-TEEMO/troll-inspector#1]
크롤링 데이터를 수집하다가 너무 많이 크롤링을 하게 되면, 사이트에서 ip를 차단하는 경우가 생김
이 점을 유의하여 크롤링 하길 바람

**Comment by gkdbssla97** [comment]
확인했습니다. interval 30분으로 두고 100 pages로 크롤링 실행
